# build stage
# image node with name build
FROM node:22-alpine AS build
WORKDIR /app
# cache package if package 
COPY package*.json  ./
RUN npm install
COPY . .
ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL
RUN npm run build
RUN ls


# run stage
FROM nginx:alpine
COPY --from=build ./app/dist /usr/share/nginx/html/
EXPOSE 80

CMD ["nginx","-g","daemon off;"]

