version: "3.8"

services:
  backend:
    image: ${IMAGE_BE}
    container_name: backend
    env_file:
      - ./env/backend.env
    restart: always
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api.themes.dangngochai.io.vn`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=le"
      - "traefik.http.services.backend.loadbalancer.server.port=5000"
  frontend:
    image: ${IMAGE_FE}
    container_name: frontend
    env_file: ./env/frontend.env
    restart: always
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`themes.dangngochai.io.vn`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=le"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
networks:
  web:
    external: true
