const express = require("express");
const router = express.Router();

// Preset themes - returned from API so FE is data-driven
const PRESET_THEMES = [
  {
    id: "light-default",
    name: "Light Default",
    emoji: "☀️",
    backgroundcolor: "#f8fafc",
    primarycolor: "#1e3a8a",
    secondarycolor: "#fbbf24",
    cardcolor: "#ffffff",
    textcolor: "#1e293b",
    bordercolor: "#e2e8f0",
    accentcolor: "#3b82f6",
  },
  {
    id: "dark-modern",
    name: "Dark Modern",
    emoji: "🌑",
    backgroundcolor: "#0f172a",
    primarycolor: "#e0f2fe",
    secondarycolor: "#22d3ee",
    cardcolor: "#1e293b",
    textcolor: "#f1f5f9",
    bordercolor: "#334155",
    accentcolor: "#06b6d4",
  },
  {
    id: "ocean-blue",
    name: "Ocean Blue",
    emoji: "🌊",
    backgroundcolor: "#0c4a6e",
    primarycolor: "#e0f2fe",
    secondarycolor: "#38bdf8",
    cardcolor: "#075985",
    textcolor: "#f0f9ff",
    bordercolor: "#0369a1",
    accentcolor: "#7dd3fc",
  },
  {
    id: "sunset",
    name: "Sunset",
    emoji: "🌅",
    backgroundcolor: "#fff7ed",
    primarycolor: "#9a3412",
    secondarycolor: "#f97316",
    cardcolor: "#ffffff",
    textcolor: "#431407",
    bordercolor: "#fed7aa",
    accentcolor: "#fb923c",
  },
  {
    id: "forest",
    name: "Forest",
    emoji: "🌿",
    backgroundcolor: "#052e16",
    primarycolor: "#dcfce7",
    secondarycolor: "#4ade80",
    cardcolor: "#14532d",
    textcolor: "#f0fdf4",
    bordercolor: "#166534",
    accentcolor: "#86efac",
  },
  {
    id: "rose-gold",
    name: "Rose Gold",
    emoji: "🌸",
    backgroundcolor: "#fff1f2",
    primarycolor: "#881337",
    secondarycolor: "#f43f5e",
    cardcolor: "#ffffff",
    textcolor: "#4c0519",
    bordercolor: "#fecdd3",
    accentcolor: "#fb7185",
  },
  {
    id: "violet-night",
    name: "Violet Night",
    emoji: "🔮",
    backgroundcolor: "#2e1065",
    primarycolor: "#f5d0fe",
    secondarycolor: "#c084fc",
    cardcolor: "#3b0764",
    textcolor: "#fdf4ff",
    bordercolor: "#6b21a8",
    accentcolor: "#d946ef",
  },
  {
    id: "mint-fresh",
    name: "Mint Fresh",
    emoji: "🍃",
    backgroundcolor: "#f0fdf4",
    primarycolor: "#065f46",
    secondarycolor: "#10b981",
    cardcolor: "#ffffff",
    textcolor: "#022c22",
    bordercolor: "#a7f3d0",
    accentcolor: "#34d399",
  },
  {
    id: "golden-hour",
    name: "Golden Hour",
    emoji: "✨",
    backgroundcolor: "#1c1917",
    primarycolor: "#fef3c7",
    secondarycolor: "#f59e0b",
    cardcolor: "#292524",
    textcolor: "#fef9c3",
    bordercolor: "#44403c",
    accentcolor: "#fbbf24",
  },
  {
    id: "arctic-ice",
    name: "Arctic Ice",
    emoji: "❄️",
    backgroundcolor: "#f0f9ff",
    primarycolor: "#0c4a6e",
    secondarycolor: "#0ea5e9",
    cardcolor: "#e0f2fe",
    textcolor: "#082f49",
    bordercolor: "#bae6fd",
    accentcolor: "#38bdf8",
  },
];

// GET /api/themes - return all preset themes
router.get("/", (req, res) => {
  res.json(PRESET_THEMES);
});

module.exports = router;
