name: CI-CD-Test

on:
  push:
    branches: ["dev/testcicd"]

jobs:
  # detect-changes:
  #   runs-on: ubuntu-latest
  #   outputs:
  #     frontend: ${{ steps.filter.outputs.frontend }}
  #     backend: ${{ steps.filter.outputs.backend }}
  # steps:
  #   - uses: actions/checkout@v4

  #   - uses: dorny/paths-filter@v3
  #     id: filter
  #     with:
  #       filters: |
  #         frontend:
  #           - 'frontend/**'
  #         backend:
  #           - 'backend/**'
  build-deploy-backend:
    # needs: detect-changes
    # if: needs.detect-changes.outputs.backend == 'true'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set backend version
        run: |
          echo "VERSION=dev-${GITHUB_SHA::7}" >> $GITHUB_ENV
          echo "IMAGE_BE=peppa2k3/theme-template-backend" >> $GITHUB_ENV

      - name: Build & push backend
        run: |
          docker build -t $IMAGE_BE:$VERSION ./backend
          docker push $IMAGE_BE:$VERSION

      - name: Deploy backend to VPS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            cd /opt/repo/mern-docker-vps-cicd-template
            git pull
            sed -i "s|IMAGE_BE=.*|IMAGE_BE=${{ env.IMAGE_BE }}:${{ env.VERSION }}|" .env
            docker compose pull backend
            docker compose up -d backend
            docker image prune -f
  build-deploy-frontend:
    # needs: detect-changes
    # if: needs.detect-changes.outputs.frontend == 'true'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set frontend version
        run: |
          echo "VERSION=dev-${GITHUB_SHA::7}" >> $GITHUB_ENV
          echo "IMAGE_FE=peppa2k3/theme-template-frontend" >> $GITHUB_ENV

      - name: Build & push frontend
        run: |
          docker build --build-arg VITE_API_URL=${{ secrets.VITE_API_URL }} -t $IMAGE_FE:$VERSION ./frontend
          docker push $IMAGE_FE:$VERSION

      - name: Deploy frontend to VPS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            cd /opt/repo/mern-docker-vps-cicd-template
            git pull
            sed -i "s|IMAGE_FE=.*|IMAGE_FE=${{ env.IMAGE_FE }}:${{ env.VERSION }}|" .env
            docker compose pull frontend
            docker compose up -d frontend
            docker image prune -f
